source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.2.2"

gem "rails", "~> 7.1.3"
gem "pg", "~> 1.5"
gem "puma", "~> 6.4"
gem "bootsnap", require: false

# API
gem "rack-cors"
gem "jbuilder"

# Auth
gem "devise"
gem "devise-jwt"
gem "pundit"

# Uploads
gem "image_processing", "~> 1.2"
gem "activestorage-cloudinary-service"

# Utilities
gem "dotenv-rails"
gem "friendly_id", "~> 5.5"

group :development, :test do
  gem "rspec-rails", "~> 6.1"
  gem "factory_bot_rails"
  gem "faker"
  gem "shoulda-matchers", "~> 6.0"
  gem "database_cleaner-active_record"
  gem "pry-rails"
  gem "rubocop", require: false
  gem "rubocop-rails", require: false
end

group :development do
  gem "listen", "~> 3.8"
  gem "spring"
end

group :test do
  gem "simplecov", require: false
end
